version: 2.1
orbs:
  mynamespace-aws: mynamespace/mynamespace-aws@0.0.1
jobs:
  build:
    docker:
      - image: 'mynamespace/python:2.7'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorum ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          from: bucket
          to: 's3://my-s3-bucket-name/prefix'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
      - aws-s3/copy:
          from: bucket/build_asset.txt
          to: 's3://my-s3-bucket-name'
          arguments: '--dryrun'
workflows:
  version: 2
  workflow:
    jobs:
      - Build 
